apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vektor
spec:
  interval: 10m
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: simple
        namespace: flux-system
      interval: 10m
  values:
    name: Vektorka
    age: 95
